<?php
// +----------------------------------------------------------------------
// | ThinkCMF [ WE CAN DO IT MORE SIMPLE ]
// +----------------------------------------------------------------------
// | Copyright (c) 2013-2018 http://www.thinkcmf.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: Powerless < wzxaini9@gmail.com>
// +----------------------------------------------------------------------
namespace app\index\controller;
use think\Controller;
use think\Db;

class LoginController extends BaseController
{
    public function _initialize()
    {
        if(session('user_id')){
            $this->redirect(url('index/index'));
        }
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 登录页面
     */
    function index()
    {
        return $this->fetch();
    }
    public function do_login(){
        if(!$this->user){
            $this->ajaxReturn(['status'=>'0','message'=>'您尚未设置密码，请先设置密码']);
        }
        $password = md5($this->request->param('password'));
        if($password == $this->user['user_password']){
            session('user_id',$this->user['user_id']);
            $this->ajaxReturn(['status'=>'1','message'=>'成功']);
        }else{
            $this->ajaxReturn(['status'=>'0','message'=>'密码错误']);
        }
    }
    public function register(){
        return $this->fetch();
    }
    public function do_register(){
        $param = $this->request->param();
        $validate = $this->validate($param,[
            'user_mobile' => 'require|mobile',
            'user_password' => 'require|number|length:6',
            'code' => 'require',
        ],[
            'user_mobile.require' => '请输入手机号',
            'user_mobile.mobile' => '手机号格式错误',
            'user_password.require' => '密码不能为空',
            'user_password.length' => '请输入6位数字密码',
            'user_password.number' => '请输入6位数字密码',
            'code.require' => '验证码不能为空',
        ]);
        if($validate !== true)
            $this->ajaxReturn(['status'=>0,'message'=>$validate]);
        if($this->user){
            $this->ajaxReturn(['status'=>'0','message'=>'您的微信号已设置过密码了哟']);
        }
        $user = Db::name('user')->where('user_mobile',$param['user_mobile'])->find();
        if(!$user){
            $this->ajaxReturn(['status'=>'0','message'=>'您无权设置密码']);
        }
        $errMsg = cmf_check_verification_code($param['user_mobile'], $param['code']);
        if (!empty($errMsg)) {
            $this->ajaxReturn(['status'=>0,'message'=>$errMsg]);
        }
        $res = Db::name('user')
            ->where(['user_id'=>$user['user_id']])
            ->update(['user_mobile'=>$param['user_mobile'],'user_openid'=>session('openid'),'user_password'=>md5($param['user_password'])]);
        if($res){
            session('user_id',$user['user_id']);
            $this->ajaxReturn(['status'=>'1','message'=>'设置成功']);
        }else{
            $this->ajaxReturn(['status'=>'0','message'=>'设置失败']);
        }
    }
}
